[workspace]

members = [
    "api",
    "atomic_counter",
    "command",
    "domain",
    "main",
    "println_logger",
    "simple_counter",
    "uppercaser",
    "db",
    "db_diesel",
]
